# This is a basic workflow to help you get started with Actions

name: Permabot

# This workflow handles notifying Permabot about changes in workflow
on:
  # Triggers the workflow on pull request events but only for the "main" branch  
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notification:
    runs-on: self-hosted
    steps:    
      - name: Notifications
        run: |
          cd ~/ircbot
          echo "Sending ${{github.event_name}} event to Permabot webserver for processing"
          curl --verbose -X POST http://localhost:8080/permabot -H 'Content-Type: application/json' -H 'X-GitHub-Event: ${{github.event_name}}' -d @${{github.event_path}}
