# This is a basic workflow to help you get started with Actions

name: Permabot

# This workflow handles notifying Permabot about changes in workflow
on:
  pull_request_target:
    types:
      [ "opened", "closed", "edited", "labeled", "unlabeled", "assigned", "unassigned", "review_requested", "review_request_removed" ]
    branches:
      [ "main" ]
  pull_request_review:
    types:
      [ "dismissed", "edited", "submitted" ]
    branches:
      [ "main" ]
  pull_request_review_comment:
    types:
      [ "created", "edited", "deleted" ]
    branches:
      [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notification:  
    runs-on: self-hosted    
    steps:              
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -U RBTools
                    
      - name: execute py script # run reviewboard.py
        run: |
          echo "Sending ${{github.event_name}} event with payload: ${{github.event_path}}"
          cp ${{github.event_path}} /u1/event.json
          python ghnotifier.py ${{github.event_name}} -p ${{github.event_path}}
          
