# This is a basic workflow to help you get started with Actions

name: Permabot

# This workflow handles notifying Permabot about changes in workflow
on:
  pull_request_target:
    types:
      [ "opened", "closed", "edited", "labeled", "unlabeled", "assigned", "unassigned", "review_requested", "review_request_removed" ]
    branches:
      [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notification:
    runs-on: self-hosted
    steps:    
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r RBTools
                    
      - name: execute py script # run reviewboard.py
        run: |
          echo "Sending ${{github.event_name}} event to ReviewBoard webserver for processing"
          python reviewboard.py ${{github.event_name}} -p @${{github.event_path}}
          
